# Generated by Django 5.1.3 on 2024-11-20 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IMS_production', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockmovement',
            name='movement_type',
            field=models.CharField(choices=[('Addition', 'Addition'), ('Subtraction', 'Subtraction')], max_length=50, verbose_name='Movement Type'),
        ),
    ]
