# Generated by Django 5.1.3 on 2025-05-09 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IMS_production', '0004_product_unique_product_name_per_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='sale_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20, verbose_name='Sale Price'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='total_revenue',
            field=models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Total Revenue'),
        ),
    ]
