from enum import StrEnum

class EmailTypes(StrEnum):
    WELCOME = "welcome"
    PASSWORD_RESET = "password_reset"
    ACCOUNT_ACTIVATION = "account_activation"
    NEWSLETTER = "newsletter"
    PROMOTIONAL = "promotional"
    TRANSACTIONAL = "transactional"
    FEEDBACK_REQUEST = "feedback_request"
    EVENT_INVITATION = "event_invitation"
    SURVEY = "survey"
    ALERT = "alert"
    REMINDER = "reminder"
    CONFIRMATION = "confirmation"
    THANK_YOU = "thank_you"
    ANNOUNCEMENT = "announcement"
    FOLLOW_UP = "follow_up"
    RECOMMENDATION = "recommendation"
    UPDATE = "update"
    CANCELLATION = "cancellation"
    SUBSCRIPTION = "subscription"
    BILLING = "billing"
    SHIPPING = "shipping"